### ISSUE TITLE
subscribeToTransactionsWithProofs throw internal error when looking since genesis block

### ISSUE THREAD

**Issue by Alex-Werner** [dashevo/js-dapi-client#139]
## Expected Behavior

As a user, I'm expecting to be able to subscribe to all transactions matching my bloomfilter since blockHeight:0 (genesis block)

## Current Behavior

Starting with {fromBlockHeight:0} throws an Internal Error. 

## Possible Solution

It might be linked to the fact that the genesis transaction is saw in Dashcore as without inputs nor outputs. 

## Steps to Reproduce (for bugs)
```js
// It is not specific to bloomfilter items.
const stream = await client.subscribeToTransactionsWithProofs(bloomfilter,  { fromBlockHeight: 0 });
```

## Context

On initial sync-up, as we do not have any first blockheight reference to speed up the sync, by default, and as the genesis block is blockHeight 0, I would expect this parameter to be the expected one.
In reality, I need to start with blockHeight:1 (which is not that much a problem, as genesis UTXO is not in UTXO DB, nor spendable). 

## Your Environment

This is not environment specific.

**Comment by shumkov** [comment]
I guess it’s a DAPI bug, not the client. Could we move this issue there?

**Comment by Alex-Werner** [comment]
I actually think it might be at a higher level, indeed, in Dashcore propulsed by insight, here some "funny" things : 

Opening block 0 is loading forever : https://insight.dashevo.org/insight/block/0 (but api works)
Opening genesis tx : https://insight.dashevo.org/insight/tx/e0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7 (and api will fail with a 404).

We can move it elsewhere, I don't really mind, but the source is, I think, upstream of DAPI.
